// Complete list of all variations with unique IDs
// This file contains only data exports and can be safely imported on the client side
export const ALL_VARIATIONS = {
  // HEAD VARIATIONS (1-102)
  heads: [
    { id: 1, name: "1960's", type: "head" },
    { id: 2, name: "24K", type: "head" },
    { id: 3, name: "???", type: "head" },
    { id: 4, name: "Ace of Spades", type: "head" },
    { id: 5, name: "Ace of Spades Ultimate", type: "head" },
    { id: 6, name: "Acid", type: "head" },
    { id: 7, name: "Acrylic", type: "head" },
    { id: 8, name: "Aqua", type: "head" },
    { id: 9, name: "Arcade", type: "head" },
    { id: 10, name: "Aztec", type: "head" },
    { id: 11, name: "Baby", type: "head" },
    { id: 12, name: "Ballerina", type: "head" },
    { id: 13, name: "Bark", type: "head" },
    { id: 14, name: "Big Brother", type: "head" },
    { id: 15, name: "Bone Daddy", type: "head" },
    { id: 16, name: "Boss", type: "head" },
    { id: 17, name: "Bowling", type: "head" },
    { id: 18, name: "Bubblegum", type: "head" },
    { id: 19, name: "Bumblebee", type: "head" },
    { id: 20, name: "Business", type: "head" },
    { id: 21, name: "Butane", type: "head" },
    { id: 22, name: "Cadillac", type: "head" },
    { id: 23, name: "Camo", type: "head" },
    { id: 24, name: "China", type: "head" },
    { id: 25, name: "Classic", type: "head" },
    { id: 26, name: "Coin", type: "head" },
    { id: 27, name: "Corroded", type: "head" },
    { id: 28, name: "Cotton Candy", type: "head" },
    { id: 29, name: "Cream", type: "head" },
    { id: 30, name: "Crimson", type: "head" },
    { id: 31, name: "Dazed Piggy", type: "head" },
    { id: 32, name: "Derelict", type: "head" },
    { id: 33, name: "Disco", type: "head" },
    { id: 34, name: "Discomania", type: "head" },
    { id: 35, name: "Dragonfly", type: "head" },
    { id: 36, name: "Shamrock", type: "head" },
    { id: 37, name: "Dualtone", type: "head" },
    { id: 38, name: "Electrik", type: "head" },
    { id: 39, name: "Ellie Mesh", type: "head" },
    { id: 40, name: "Exposed", type: "head" },
    { id: 41, name: "Flaked", type: "head" },
    { id: 42, name: "Frost King", type: "head" },
    { id: 43, name: "Gold", type: "head" },
    { id: 44, name: "Goth Boi", type: "head" },
    { id: 45, name: "Grilled", type: "head" },
    { id: 46, name: "Hacker", type: "head" },
    { id: 47, name: "Handbag", type: "head" },
    { id: 48, name: "Hello Bubblegum Kitty", type: "head" },
    { id: 49, name: "Hello Gray Kitty", type: "head" },
    { id: 50, name: "Hello Kitty", type: "head" },
    { id: 51, name: "Honeycomb", type: "head" },
    { id: 52, name: "Horror Clown", type: "head" },
    { id: 53, name: "Hurricane", type: "head" },
    { id: 54, name: "Independent", type: "head" },
    { id: 55, name: "Inspector", type: "head" },
    { id: 56, name: "Jalapeno", type: "head" },
    { id: 57, name: "Jelly Bean", type: "head" },
    { id: 58, name: "Jester", type: "head" },
    { id: 59, name: "Jungle", type: "head" },
    { id: 60, name: "Ketchup", type: "head" },
    { id: 61, name: "Laser", type: "head" },
    { id: 62, name: "Light Steel", type: "head" },
    { id: 63, name: "Loquat", type: "head" },
    { id: 64, name: "Love", type: "head" },
    { id: 65, name: "Lustre", type: "head" },
    { id: 66, name: "Mango", type: "head" },
    { id: 67, name: "Mathematics", type: "head" },
    { id: 68, name: "MEK", type: "head" },
    { id: 69, name: "Mercury", type: "head" },
    { id: 70, name: "Million", type: "head" },
    { id: 71, name: "Night", type: "head" },
    { id: 72, name: "Nuclear", type: "head" },
    { id: 73, name: "Paisley", type: "head" },
    { id: 74, name: "Party", type: "head" },
    { id: 75, name: "Phantom", type: "head" },
    { id: 76, name: "Plated", type: "head" },
    { id: 77, name: "Porcelain", type: "head" },
    { id: 78, name: "Pork", type: "head" },
    { id: 79, name: "Puzzle", type: "head" },
    { id: 80, name: "Quartz", type: "head" },
    { id: 81, name: "Robot", type: "head" },
    { id: 82, name: "Rover", type: "head" },
    { id: 83, name: "Rubber", type: "head" },
    { id: 84, name: "Rubber Duck", type: "head" },
    { id: 85, name: "Sack", type: "head" },
    { id: 86, name: "Scratchy", type: "head" },
    { id: 87, name: "Shell", type: "head" },
    { id: 88, name: "Silver", type: "head" },
    { id: 89, name: "Snitch", type: "head" },
    { id: 90, name: "Stark", type: "head" },
    { id: 91, name: "Stinky", type: "head" },
    { id: 92, name: "Stitch", type: "head" },
    { id: 93, name: "Titanium", type: "head" },
    { id: 94, name: "UV", type: "head" },
    { id: 95, name: "Vader", type: "head" },
    { id: 96, name: "Valentine", type: "head" },
    { id: 97, name: "Vanilla", type: "head" },
    { id: 98, name: "Vegas", type: "head" },
    { id: 99, name: "Vomit", type: "head" },
    { id: 100, name: "Wave", type: "head" },
    { id: 101, name: "Xmek", type: "head" },
    { id: 102, name: "Zed", type: "head" },
  ],

  // BODY VARIATIONS (103-214)
  bodies: [
    { id: 103, name: "1960's", type: "body" },
    { id: 104, name: "24K", type: "body" },
    { id: 105, name: "???", type: "body" },
    { id: 106, name: "Ace of Spades", type: "body" },
    { id: 107, name: "Ace of Spades Ultimate", type: "body" },
    { id: 108, name: "Acid", type: "body" },
    { id: 109, name: "Acrylic", type: "body" },
    { id: 110, name: "Aqua", type: "body" },
    { id: 111, name: "Arcade", type: "body" },
    { id: 112, name: "Argyle", type: "body" },
    { id: 113, name: "Aztec", type: "body" },
    { id: 114, name: "Baby", type: "body" },
    { id: 115, name: "Ballerina", type: "body" },
    { id: 116, name: "Bark", type: "body" },
    { id: 117, name: "Big Brother", type: "body" },
    { id: 118, name: "Black", type: "body" },
    { id: 119, name: "Bloodlines", type: "body" },
    { id: 120, name: "Bone Daddy", type: "body" },
    { id: 121, name: "Boss", type: "body" },
    { id: 122, name: "Bowling", type: "body" },
    { id: 123, name: "Bubblegum", type: "body" },
    { id: 124, name: "Bumblebee", type: "body" },
    { id: 125, name: "Business", type: "body" },
    { id: 126, name: "Butane", type: "body" },
    { id: 127, name: "Cadillac", type: "body" },
    { id: 128, name: "Camo", type: "body" },
    { id: 129, name: "China", type: "body" },
    { id: 130, name: "Classic", type: "body" },
    { id: 131, name: "Coin", type: "body" },
    { id: 132, name: "Corroded", type: "body" },
    { id: 133, name: "Cotton Candy", type: "body" },
    { id: 134, name: "Cream", type: "body" },
    { id: 135, name: "Crimson", type: "body" },
    { id: 136, name: "Dazed Piggy", type: "body" },
    { id: 137, name: "Derelict", type: "body" },
    { id: 138, name: "Disco", type: "body" },
    { id: 139, name: "Discomania", type: "body" },
    { id: 140, name: "Dragonfly", type: "body" },
    { id: 141, name: "Shamrock", type: "body" },
    { id: 142, name: "Dualtone", type: "body" },
    { id: 143, name: "Electrik", type: "body" },
    { id: 144, name: "Ellie Mesh", type: "body" },
    { id: 145, name: "Exposed", type: "body" },
    { id: 146, name: "Flaked", type: "body" },
    { id: 147, name: "Frost King", type: "body" },
    { id: 148, name: "Gold", type: "body" },
    { id: 149, name: "Goth Boi", type: "body" },
    { id: 150, name: "Grilled", type: "body" },
    { id: 151, name: "Hacker", type: "body" },
    { id: 152, name: "Handbag", type: "body" },
    { id: 153, name: "Hello Bubblegum Kitty", type: "body" },
    { id: 154, name: "Hello Gray Kitty", type: "body" },
    { id: 155, name: "Hello Kitty", type: "body" },
    { id: 156, name: "Honeycomb", type: "body" },
    { id: 157, name: "Horror Clown", type: "body" },
    { id: 158, name: "Hurricane", type: "body" },
    { id: 159, name: "Independent", type: "body" },
    { id: 160, name: "Inspector", type: "body" },
    { id: 161, name: "Jalapeno", type: "body" },
    { id: 162, name: "Jelly Bean", type: "body" },
    { id: 163, name: "Jester", type: "body" },
    { id: 164, name: "Jungle", type: "body" },
    { id: 165, name: "Ketchup", type: "body" },
    { id: 166, name: "Laser", type: "body" },
    { id: 167, name: "Light Steel", type: "body" },
    { id: 168, name: "Loquat", type: "body" },
    { id: 169, name: "Love", type: "body" },
    { id: 170, name: "Lustre", type: "body" },
    { id: 171, name: "Mango", type: "body" },
    { id: 172, name: "Mathematics", type: "body" },
    { id: 173, name: "MEK", type: "body" },
    { id: 174, name: "Mercury", type: "body" },
    { id: 175, name: "Million", type: "body" },
    { id: 176, name: "Night", type: "body" },
    { id: 177, name: "Nuclear", type: "body" },
    { id: 178, name: "Paisley", type: "body" },
    { id: 179, name: "Party", type: "body" },
    { id: 180, name: "Phantom", type: "body" },
    { id: 181, name: "Plated", type: "body" },
    { id: 182, name: "Porcelain", type: "body" },
    { id: 183, name: "Pork", type: "body" },
    { id: 184, name: "Purple", type: "body" },
    { id: 185, name: "Puzzle", type: "body" },
    { id: 186, name: "Quartz", type: "body" },
    { id: 187, name: "Robot", type: "body" },
    { id: 188, name: "Rover", type: "body" },
    { id: 189, name: "Rubber", type: "body" },
    { id: 190, name: "Rubber Duck", type: "body" },
    { id: 191, name: "Sack", type: "body" },
    { id: 192, name: "Scratchy", type: "body" },
    { id: 193, name: "Shell", type: "body" },
    { id: 194, name: "Silver", type: "body" },
    { id: 195, name: "Snitch", type: "body" },
    { id: 196, name: "Stark", type: "body" },
    { id: 197, name: "Stinky", type: "body" },
    { id: 198, name: "Stitch", type: "body" },
    { id: 199, name: "Titanium", type: "body" },
    { id: 200, name: "Translucent", type: "body" },
    { id: 201, name: "Turtle", type: "body" },
    { id: 202, name: "UV", type: "body" },
    { id: 203, name: "Vader", type: "body" },
    { id: 204, name: "Valentine", type: "body" },
    { id: 205, name: "Vanilla", type: "body" },
    { id: 206, name: "Vegas", type: "body" },
    { id: 207, name: "Vomit", type: "body" },
    { id: 208, name: "Wave", type: "body" },
    { id: 209, name: "Xmek", type: "body" },
    { id: 210, name: "Yellow Glass", type: "body" },
    { id: 211, name: "Zed", type: "body" },
    { id: 212, name: "Brown", type: "body" },
    { id: 213, name: "Green", type: "body" },
    { id: 214, name: "Light Gray", type: "body" },
  ],

  // ITEM VARIATIONS (215-309)
  items: [
    { id: 215, name: "1960's", type: "item" },
    { id: 216, name: "24K", type: "item" },
    { id: 217, name: "???", type: "item" },
    { id: 218, name: "Ace of Spades", type: "item" },
    { id: 219, name: "Ace of Spades Ultimate", type: "item" },
    { id: 220, name: "Acid", type: "item" },
    { id: 221, name: "Acrylic", type: "item" },
    { id: 222, name: "Aqua", type: "item" },
    { id: 223, name: "Arcade", type: "item" },
    { id: 224, name: "Aztec", type: "item" },
    { id: 225, name: "Baby", type: "item" },
    { id: 226, name: "Ballerina", type: "item" },
    { id: 227, name: "Bark", type: "item" },
    { id: 228, name: "Big Brother", type: "item" },
    { id: 229, name: "Bone Daddy", type: "item" },
    { id: 230, name: "Boss", type: "item" },
    { id: 231, name: "Bowling", type: "item" },
    { id: 232, name: "Bubblegum", type: "item" },
    { id: 233, name: "Bumblebee", type: "item" },
    { id: 234, name: "Business", type: "item" },
    { id: 235, name: "Butane", type: "item" },
    { id: 236, name: "Camo", type: "item" },
    { id: 237, name: "China", type: "item" },
    { id: 238, name: "Classic", type: "item" },
    { id: 239, name: "Coin", type: "item" },
    { id: 240, name: "Corroded", type: "item" },
    { id: 241, name: "Cotton Candy", type: "item" },
    { id: 242, name: "Crimson", type: "item" },
    { id: 243, name: "Dazed Piggy", type: "item" },
    { id: 244, name: "Derelict", type: "item" },
    { id: 245, name: "Disco", type: "item" },
    { id: 246, name: "Discomania", type: "item" },
    { id: 247, name: "Dragonfly", type: "item" },
    { id: 248, name: "Shamrock", type: "item" },
    { id: 249, name: "Dualtone", type: "item" },
    { id: 250, name: "Electrik", type: "item" },
    { id: 251, name: "Exposed", type: "item" },
    { id: 252, name: "Flaked", type: "item" },
    { id: 253, name: "Frost King", type: "item" },
    { id: 254, name: "Gold", type: "item" },
    { id: 255, name: "Goth Boi", type: "item" },
    { id: 256, name: "Hacker", type: "item" },
    { id: 257, name: "Handbag", type: "item" },
    { id: 258, name: "Hello Bubblegum Kitty", type: "item" },
    { id: 259, name: "Hello Gray Kitty", type: "item" },
    { id: 260, name: "Hello Kitty", type: "item" },
    { id: 261, name: "Honeycomb", type: "item" },
    { id: 262, name: "Horror Clown", type: "item" },
    { id: 263, name: "Hurricane", type: "item" },
    { id: 264, name: "Independent", type: "item" },
    { id: 265, name: "Inspector", type: "item" },
    { id: 266, name: "Jelly Bean", type: "item" },
    { id: 267, name: "Jester", type: "item" },
    { id: 268, name: "Jungle", type: "item" },
    { id: 269, name: "Ketchup", type: "item" },
    { id: 270, name: "Laser", type: "item" },
    { id: 271, name: "Light Steel", type: "item" },
    { id: 272, name: "Loquat", type: "item" },
    { id: 273, name: "Love", type: "item" },
    { id: 274, name: "Lustre", type: "item" },
    { id: 275, name: "Mathematics", type: "item" },
    { id: 276, name: "MEK", type: "item" },
    { id: 277, name: "Mercury", type: "item" },
    { id: 278, name: "Million", type: "item" },
    { id: 279, name: "Night", type: "item" },
    { id: 280, name: "Nuclear", type: "item" },
    { id: 281, name: "Paisley", type: "item" },
    { id: 282, name: "Party", type: "item" },
    { id: 283, name: "Phantom", type: "item" },
    { id: 284, name: "Plated", type: "item" },
    { id: 285, name: "Porcelain", type: "item" },
    { id: 286, name: "Pork", type: "item" },
    { id: 287, name: "Puzzle", type: "item" },
    { id: 288, name: "Quartz", type: "item" },
    { id: 289, name: "Robot", type: "item" },
    { id: 290, name: "Rubber", type: "item" },
    { id: 291, name: "Rubber Duck", type: "item" },
    { id: 292, name: "Sack", type: "item" },
    { id: 293, name: "Scratchy", type: "item" },
    { id: 294, name: "Silver", type: "item" },
    { id: 295, name: "Snitch", type: "item" },
    { id: 296, name: "Stinky", type: "item" },
    { id: 297, name: "Stitch", type: "item" },
    { id: 298, name: "Titanium", type: "item" },
    { id: 299, name: "UV", type: "item" },
    { id: 300, name: "Vader", type: "item" },
    { id: 301, name: "Valentine", type: "item" },
    { id: 302, name: "Vanilla", type: "item" },
    { id: 303, name: "Vegas", type: "item" },
    { id: 304, name: "Vomit", type: "item" },
    { id: 305, name: "Wave", type: "item" },
    { id: 306, name: "Xmek", type: "item" },
    { id: 307, name: "Zed", type: "item" },
    { id: 308, name: "None", type: "item" },
    { id: 309, name: "Green", type: "item" },
  ],
};