/**
 * Maps variation names to their image filenames
 * Auto-generated from files in public/variation-images
 */
export const VARIATION_IMAGE_MAP: Record<string, string> = {
  '007': '007.png',
  '101.1 FM': '101.1_fm.png',
  '101.1FM': '101.1_fm.png',
  '101.1_FM': '101.1_fm.png',
  '1960S': '1960s.png',
  '2001': '2001.png',
  '24K': '24k.png',
  'ABOMINABLE': 'abominable.png',
  'ACE OF SPADES ULTIMA': 'ace_of_spades_ultima.png',
  'ACE OF SPADES ULTIMATE': 'ace_of_spades_ultimate.png',
  'ACE OF SPADES': 'ace_of_spades.png',
  'ACEOFSPADES': 'ace_of_spades.png',
  'ACEOFSPADESULTIMA': 'ace_of_spades_ultima.png',
  'ACEOFSPADESULTIMATE': 'ace_of_spades_ultimate.png',
  'ACE_OF_SPADES': 'ace_of_spades.png',
  'ACE_OF_SPADES_ULTIMA': 'ace_of_spades_ultima.png',
  'ACE_OF_SPADES_ULTIMATE': 'ace_of_spades_ultimate.png',
  'ACRYLIC': 'acrylic.png',
  'ALBINO': 'albino.png',
  'ANGLER': 'angler.png',
  'AQUA': 'aqua.png',
  'ARCADE': 'arcade.png',
  'ARCTIC': 'arctic.png',
  'AZTEC': 'aztec.png',
  'BABY': 'baby.png',
  'BAG': 'bag.png',
  'BALLERINA': 'ballerina.png',
  'BARK': 'bark.png',
  'BIG BROTHER': 'big_brother.png',
  'BIGBROTHER': 'big_brother.png',
  'BIG_BROTHER': 'big_brother.png',
  'BLACK & WHITE': 'black_&_white.png',
  'BLACK PARADE': 'black_parade.png',
  'BLACK&WHITE': 'black_&_white.png',
  'BLACK': 'black.png',
  'BLACKPARADE': 'black_parade.png',
  'BLACK_&_WHITE': 'black_&_white.png',
  'BLACK_PARADE': 'black_parade.png',
  'BLASTERS': 'blasters.png',
  'BLING': 'bling.png',
  'BLOOD': 'blood.png',
  'BLUSH': 'blush.png',
  'BONE DADDY': 'bone_daddy.png',
  'BONE': 'bone.png',
  'BONEBOX': 'bonebox.png',
  'BONEDADDY': 'bone_daddy.png',
  'BONE_DADDY': 'bone_daddy.png',
  'BOOMBOX': 'boombox.png',
  'BOSS': 'boss.png',
  'BOWLING': 'bowling.png',
  'BROADCAST': 'broadcast.png',
  'BUBBLEGUM': 'bubblegum.png',
  'BUMBLE BIRD': 'bumble_bird.png',
  'BUMBLEBEE': 'bumblebee.png',
  'BUMBLEBIRD': 'bumble_bird.png',
  'BUMBLE_BIRD': 'bumble_bird.png',
  'BURNT ULTIMATE': 'burnt_ultimate.png',
  'BURNT': 'burnt.png',
  'BURNTULTIMATE': 'burnt_ultimate.png',
  'BURNT_ULTIMATE': 'burnt_ultimate.png',
  'BUSINESS': 'business.png',
  'BUTANE': 'butane.png',
  'BUTTERFLY': 'butterfly.png',
  'CADILLAC': 'cadillac.png',
  'CAMO': 'camo.png',
  'CANNON ULTIMATE': 'cannon_ultimate.png',
  'CANNON': 'cannon.png',
  'CANNONULTIMATE': 'cannon_ultimate.png',
  'CANNON_ULTIMATE': 'cannon_ultimate.png',
  'CARBON': 'carbon.png',
  'CARBONITE': 'carbonite.png',
  'CARTOON': 'cartoon.png',
  'CARTOONICHROME': 'cartoonichrome.png',
  'CARVING ULTIMATE': 'carving_ultimate.png',
  'CARVING': 'carving.png',
  'CARVINGULTIMATE': 'carving_ultimate.png',
  'CARVING_ULTIMATE': 'carving_ultimate.png',
  'CHEETAH': 'cheetah.png',
  'CHINA': 'china.png',
  'CHROME ULTIMATE': 'chrome_ultimate.png',
  'CHROME': 'chrome.png',
  'CHROMEULTIMATE': 'chrome_ultimate.png',
  'CHROME_ULTIMATE': 'chrome_ultimate.png',
  'CHROMIUM': 'chromium.png',
  'CLASSIC': 'classic.png',
  'COIN': 'coin.png',
  'CONCRETE': 'concrete.png',
  'CONTRACTOR': 'contractor.png',
  'CORRODED': 'corroded.png',
  'COTTON CANDY': 'cotton_candy.png',
  'COTTONCANDY': 'cotton_candy.png',
  'COTTON_CANDY': 'cotton_candy.png',
  'COUCH': 'couch.png',
  'COUSIN ITT': 'cousin_itt.png',
  'COUSINITT': 'cousin_itt.png',
  'COUSIN_ITT': 'cousin_itt.png',
  'CREAM': 'cream.png',
  'CRIMSON': 'crimson.png',
  'CROW': 'crow.png',
  'CRYSTAL CAMO': 'crystal_camo.png',
  'CRYSTAL CLEAR': 'crystal_clear.png',
  'CRYSTALCAMO': 'crystal_camo.png',
  'CRYSTALCLEAR': 'crystal_clear.png',
  'CRYSTAL_CAMO': 'crystal_camo.png',
  'CRYSTAL_CLEAR': 'crystal_clear.png',
  'CUBES': 'cubes.png',
  'DAMASCUS': 'damascus.png',
  'DAZED PIGGY': 'dazed_piggy.png',
  'DAZEDPIGGY': 'dazed_piggy.png',
  'DAZED_PIGGY': 'dazed_piggy.png',
  'DEEP SPACE': 'deep_space.png',
  'DEEPSPACE': 'deep_space.png',
  'DEEP_SPACE': 'deep_space.png',
  'DENIM': 'denim.png',
  'DERELICT': 'derelict.png',
  'DESUFNOC': 'desufnoc.png',
  'DISCO': 'disco.png',
  'DISCOMANIA': 'discomania.png',
  'DOOM': 'doom.png',
  'DR.': 'dr..png',
  'DRAGONFLY': 'dragonfly.png',
  'DRILL': 'drill.png',
  'DRIP': 'drip.png',
  'DUALTONE': 'dualtone.png',
  'EARTH': 'earth.png',
  'ELECTRIK': 'electrik.png',
  'ELLIE MESH': 'ellie_mesh.png',
  'ELLIEMESH': 'ellie_mesh.png',
  'ELLIE_MESH': 'ellie_mesh.png',
  'EXPOSED': 'exposed.png',
  'EYES': 'eyes.png',
  'FILM': 'film.png',
  'FIREBIRD': 'firebird.png',
  'FLAKED': 'flaked.png',
  'FOIL': 'foil.png',
  'FOREST': 'forest.png',
  'FOURZIN': 'fourzin.png',
  'FROST CAGE': 'frost_cage.png',
  'FROST KING': 'frost_king.png',
  'FROSTBIT': 'frostbit.png',
  'FROSTCAGE': 'frost_cage.png',
  'FROSTED': 'frosted.png',
  'FROSTKING': 'frost_king.png',
  'FROST_CAGE': 'frost_cage.png',
  'FROST_KING': 'frost_king.png',
  'FURY': 'fury.png',
  'GATSBY ULTIMATE': 'gatsby_ultimate.png',
  'GATSBY': 'gatsby.png',
  'GATSBYULTIMATE': 'gatsby_ultimate.png',
  'GATSBY_ULTIMATE': 'gatsby_ultimate.png',
  'GIGER': 'giger.png',
  'GOBLIN': 'goblin.png',
  'GOLD': 'gold.png',
  'GOLDEN GUNS ULTIMATE': 'golden_guns_ultimate.png',
  'GOLDEN GUNS': 'golden_guns.png',
  'GOLDENGUNS': 'golden_guns.png',
  'GOLDENGUNSULTIMATE': 'golden_guns_ultimate.png',
  'GOLDEN_GUNS': 'golden_guns.png',
  'GOLDEN_GUNS_ULTIMATE': 'golden_guns_ultimate.png',
  'GONE': 'gone.png',
  'GRANITE': 'granite.png',
  'GRASS': 'grass.png',
  'GRATE': 'grate.png',
  'HACKER': 'hacker.png',
  'HADES': 'hades.png',
  'HAL': 'hal.png',
  'HAMMERHEAT': 'hammerheat.png',
  'HAPPYMEAL': 'happymeal.png',
  'HAWK': 'hawk.png',
  'HEART': 'heart.png',
  'HEATMAP': 'heatmap.png',
  'HEATWAVE ULTIMATE': 'heatwave_ultimate.png',
  'HEATWAVE': 'heatwave.png',
  'HEATWAVEULTIMATE': 'heatwave_ultimate.png',
  'HEATWAVE_ULTIMATE': 'heatwave_ultimate.png',
  'HEFNER': 'hefner.png',
  'HELIOTROPIUM': 'heliotropium.png',
  'HIGHLIGHTS': 'highlights.png',
  'HOLOGRAPHIC': 'holographic.png',
  'HYDRA': 'hydra.png',
  'ICED': 'iced.png',
  'ICON': 'icon.png',
  'INNER RAINBOW': 'inner_rainbow.png',
  'INNERRAINBOW': 'inner_rainbow.png',
  'INNER_RAINBOW': 'inner_rainbow.png',
  'IRON': 'iron.png',
  'IVORY': 'ivory.png',
  'JAMES': 'james.png',
  'JEFF': 'jeff.png',
  'JOLLY RANCHER': 'jolly_rancher.png',
  'JOLLYRANCHER': 'jolly_rancher.png',
  'JOLLY_RANCHER': 'jolly_rancher.png',
  'JOURNEY': 'journey.png',
  'JUST WREN': 'just_wren.png',
  'JUSTWREN': 'just_wren.png',
  'JUST_WREN': 'just_wren.png',
  'KEVLAR': 'kevlar.png',
  'KING TUT': 'king_tut.png',
  'KINGTUT': 'king_tut.png',
  'KING_TUT': 'king_tut.png',
  'LAZER': 'lazer.png',
  'LEELOO': 'leeloo.png',
  'LICH': 'lich.png',
  'LIGHT': 'light.png',
  'LIGHTNING': 'lightning.png',
  'LINKINATOR 3000': 'linkinator_3000.png',
  'LINKINATOR3000': 'linkinator_3000.png',
  'LINKINATOR_3000': 'linkinator_3000.png',
  'LIQUID LAVENDER': 'liquid_lavender.png',
  'LIQUIDLAVENDER': 'liquid_lavender.png',
  'LIQUID_LAVENDER': 'liquid_lavender.png',
  'LIZARD': 'lizard.png',
  'LOG': 'log.png',
  'LORD': 'lord.png',
  'LUMBERJACK': 'lumberjack.png',
  'LUNA': 'luna.png',
  'LUXURY ULTIMATE': 'luxury_ultimate.png',
  'LUXURY': 'luxury.png',
  'LUXURYULTIMATE': 'luxury_ultimate.png',
  'LUXURY_ULTIMATE': 'luxury_ultimate.png',
  'LV-426': 'lv-426.png',
  'MAC & CHEESE': 'mac_&_cheese.png',
  'MAC&CHEESE': 'mac_&_cheese.png',
  'MAC_&_CHEESE': 'mac_&_cheese.png',
  'MAGMA': 'magma.png',
  'MAHOGANY': 'mahogany.png',
  'MAJESTY': 'majesty.png',
  'MAPLE': 'maple.png',
  'MAPS': 'maps.png',
  'MARBLE': 'marble.png',
  'MARS ATTACKS': 'mars_attacks.png',
  'MARSATTACKS': 'mars_attacks.png',
  'MARS_ATTACKS': 'mars_attacks.png',
  'MATTE': 'matte.png',
  'MAZE': 'maze.png',
  'MEAT': 'meat.png',
  'MERCURY': 'mercury.png',
  'MESH': 'mesh.png',
  'MICROPHONE': 'microphone.png',
  'MILK': 'milk.png',
  'MINI ME': 'mini_me.png',
  'MINIME': 'mini_me.png',
  'MINI_ME': 'mini_me.png',
  'MINT': 'mint.png',
  'MOLTEN CORE': 'molten_core.png',
  'MOLTENCORE': 'molten_core.png',
  'MOLTEN_CORE': 'molten_core.png',
  'MOTH': 'moth.png',
  'MUGGED': 'mugged.png',
  'NEAR SPACE': 'near_space.png',
  'NEARSPACE': 'near_space.png',
  'NEAR_SPACE': 'near_space.png',
  'NEON FLAMINGO': 'neon_flamingo.png',
  'NEONFLAMINGO': 'neon_flamingo.png',
  'NEON_FLAMINGO': 'neon_flamingo.png',
  'NIGHT VISION': 'night_vision.png',
  'NIGHTSTALKER': 'nightstalker.png',
  'NIGHTVISION': 'night_vision.png',
  'NIGHT_VISION': 'night_vision.png',
  'NIL': 'nil.png',
  'NONE': 'none.png',
  'NOOB': 'noob.png',
  'NOTHING': 'nothing.png',
  'NUCLEAR': 'nuclear.png',
  'NUGGETS': 'nuggets.png',
  'NUKE': 'nuke.png',
  'NULL': 'null.png',
  'NYAN ULTIMATE': 'nyan_ultimate.png',
  'NYAN': 'nyan.png',
  'NYANULTIMATE': 'nyan_ultimate.png',
  'NYAN_ULTIMATE': 'nyan_ultimate.png',
  'OBLITERATOR': 'obliterator.png',
  'OBSIDIAN': 'obsidian.png',
  'OCEAN': 'ocean.png',
  'OE DARK': 'oe_dark.png',
  'OE LIGHT': 'oe_light.png',
  'OEDARK': 'oe_dark.png',
  'OELIGHT': 'oe_light.png',
  'OE_DARK': 'oe_dark.png',
  'OE_LIGHT': 'oe_light.png',
  'OIL': 'oil.png',
  'OL FAITHFUL': 'ol_faithful.png',
  'OLFAITHFUL': 'ol_faithful.png',
  'OL_FAITHFUL': 'ol_faithful.png',
  'OOMPAH': 'oompah.png',
  'OOZE': 'ooze.png',
  'ORNAMENT': 'ornament.png',
  'PALACE': 'palace.png',
  'PAPARAZZI': 'paparazzi.png',
  'PAUL ULTIMATE': 'paul_ultimate.png',
  'PAUL': 'paul.png',
  'PAULULTIMATE': 'paul_ultimate.png',
  'PAUL_ULTIMATE': 'paul_ultimate.png',
  'PAWN SHOP': 'pawn_shop.png',
  'PAWNSHOP': 'pawn_shop.png',
  'PAWN_SHOP': 'pawn_shop.png',
  'PEACOCK ULTIMATE': 'peacock_ultimate.png',
  'PEACOCK': 'peacock.png',
  'PEACOCKULTIMATE': 'peacock_ultimate.png',
  'PEACOCK_ULTIMATE': 'peacock_ultimate.png',
  'PEARL': 'pearl.png',
  'PEPPERMINT': 'peppermint.png',
  'PHOENIX': 'phoenix.png',
  'PIE': 'pie.png',
  'PIZZA': 'pizza.png',
  'PLASTIK': 'plastik.png',
  'PLATE': 'plate.png',
  'PLUSH ULTIMATE': 'plush_ultimate.png',
  'PLUSH': 'plush.png',
  'PLUSHULTIMATE': 'plush_ultimate.png',
  'PLUSH_ULTIMATE': 'plush_ultimate.png',
  'POKER': 'poker.png',
  'POLISHED': 'polished.png',
  'POP': 'pop.png',
  'PORCELAIN': 'porcelain.png',
  'PRICKLES': 'prickles.png',
  'PRINCESS': 'princess.png',
  'PROJECTIONIST': 'projectionist.png',
  'PROM': 'prom.png',
  'PURPLEX': 'purplex.png',
  'PYLONS': 'pylons.png',
  'PYREX': 'pyrex.png',
  'QQQ': 'qqq.png',
  'QUILT': 'quilt.png',
  'R&B': 'r&b.png',
  'RADIANCE': 'radiance.png',
  'RAINBOW MORPHO': 'rainbow_morpho.png',
  'RAINBOWMORPHO': 'rainbow_morpho.png',
  'RAINBOW_MORPHO': 'rainbow_morpho.png',
  'RATTLER': 'rattler.png',
  'RECON': 'recon.png',
  'RING BLUE': 'ring_blue.png',
  'RING GREEN': 'ring_green.png',
  'RING RED': 'ring_red.png',
  'RINGBLUE': 'ring_blue.png',
  'RINGGREEN': 'ring_green.png',
  'RINGRED': 'ring_red.png',
  'RING_BLUE': 'ring_blue.png',
  'RING_GREEN': 'ring_green.png',
  'RING_RED': 'ring_red.png',
  'ROSE': 'rose.png',
  'ROSS': 'ross.png',
  'ROYAL': 'royal.png',
  'RUG': 'rug.png',
  'RUST': 'rust.png',
  'SAHARA': 'sahara.png',
  'SAND': 'sand.png',
  'SAP': 'sap.png',
  'SATELLITE': 'satellite.png',
  'SAW': 'saw.png',
  'SCISSORS': 'scissors.png',
  'SCREAMO': 'screamo.png',
  'SEABISCUIT': 'seabiscuit.png',
  'SEAFOAM': 'seafoam.png',
  'SHAMROCK': 'shamrock.png',
  'SHARK': 'shark.png',
  'SHIPPED': 'shipped.png',
  'SILENT FILM': 'silent_film.png',
  'SILENTFILM': 'silent_film.png',
  'SILENT_FILM': 'silent_film.png',
  'SILICON': 'silicon.png',
  'SILVER': 'silver.png',
  'SIR': 'sir.png',
  'SKULL ULTIMATE': 'skull_ultimate.png',
  'SKULLULTIMATE': 'skull_ultimate.png',
  'SKULL_ULTIMATE': 'skull_ultimate.png',
  'SKY': 'sky.png',
  'SLEET': 'sleet.png',
  'SMURF': 'smurf.png',
  'SNAPSHOT': 'snapshot.png',
  'SNOW': 'snow.png',
  'SOUL': 'soul.png',
  'SPAGHETTI': 'spaghetti.png',
  'SPECTRUM': 'spectrum.png',
  'SPLATTER': 'splatter.png',
  'STAINED GLASS': 'stained_glass.png',
  'STAINEDGLASS': 'stained_glass.png',
  'STAINED_GLASS': 'stained_glass.png',
  'STARS': 'stars.png',
  'STEAM': 'steam.png',
  'STERLING': 'sterling.png',
  'STICKY': 'sticky.png',
  'STOCK': 'stock.png',
  'STOLEN': 'stolen.png',
  'STONE': 'stone.png',
  'SUN': 'sun.png',
  'SUNSET': 'sunset.png',
  'TACTICAL': 'tactical.png',
  'TANGERINE': 'tangerine.png',
  'TARPIE': 'tarpie.png',
  'TASER': 'taser.png',
  'TAT': 'tat.png',
  'TECHNICOLOR': 'technicolor.png',
  'TERMINATOR': 'terminator.png',
  'TEST TRACK': 'test_track.png',
  'TESTTRACK': 'test_track.png',
  'TEST_TRACK': 'test_track.png',
  'THE LETHAL DIMENSION': 'the_lethal_dimension.png',
  'THE RAM': 'the_ram.png',
  'THELETHALDIMENSION': 'the_lethal_dimension.png',
  'THERAM': 'the_ram.png',
  'THE_LETHAL_DIMENSION': 'the_lethal_dimension.png',
  'THE_RAM': 'the_ram.png',
  'TICKLE': 'tickle.png',
  'TIE DYE': 'tie_dye.png',
  'TIEDYE': 'tie_dye.png',
  'TIE_DYE': 'tie_dye.png',
  'TILES': 'tiles.png',
  'TRAPPED': 'trapped.png',
  'TRON': 'tron.png',
  'ULTIMATE INSTRUMENTS': 'ultimate_instruments.png',
  'ULTIMATE WEAPONRY': 'ultimate_weaponry.png',
  'ULTIMATEINSTRUMENTS': 'ultimate_instruments.png',
  'ULTIMATEWEAPONRY': 'ultimate_weaponry.png',
  'ULTIMATE_INSTRUMENTS': 'ultimate_instruments.png',
  'ULTIMATE_WEAPONRY': 'ultimate_weaponry.png',
  'VAMPIRE': 'vampire.png',
  'VANISHED': 'vanished.png',
  'VAPOR': 'vapor.png',
  'VICTORIA': 'victoria.png',
  'WAVES': 'waves.png',
  'WHISKEY': 'whiskey.png',
  'WHITE': 'white.png',
  'WHITEOUT': 'whiteout.png',
  'WHO': 'who.png',
  'WINGS ULTIMATE': 'wings_ultimate.png',
  'WINGS': 'wings.png',
  'WINGSULTIMATE': 'wings_ultimate.png',
  'WINGS_ULTIMATE': 'wings_ultimate.png',
  'WIRES': 'wires.png',
  'X RAY ULTIMATE': 'x_ray_ultimate.png',
  'X RAY': 'x_ray.png',
  'XRAY': 'x_ray.png',
  'XRAYULTIMATE': 'x_ray_ultimate.png',
  'X_RAY': 'x_ray.png',
  'X_RAY_ULTIMATE': 'x_ray_ultimate.png',
  // Default fallback
  'DEFAULT': 'default.png'
};