import { mutation, query } from "./_generated/server";
import { v } from "convex/values";

// Complete list of all variations with unique IDs
export const ALL_VARIATIONS = {
  // HEAD VARIATIONS (1-102)
  heads: [
    { id: 1, name: "1960's", type: "head" },
    { id: 2, name: "24K", type: "head" },
    { id: 3, name: "???", type: "head" },
    { id: 4, name: "Ace of Spades", type: "head" },
    { id: 5, name: "Ace of Spades Ultimate", type: "head" },
    { id: 6, name: "Acid", type: "head" },
    { id: 7, name: "Acrylic", type: "head" },
    { id: 8, name: "Aqua", type: "head" },
    { id: 9, name: "Arcade", type: "head" },
    { id: 10, name: "Aztec", type: "head" },
    { id: 11, name: "Baby", type: "head" },
    { id: 12, name: "Ballerina", type: "head" },
    { id: 13, name: "Bark", type: "head" },
    { id: 14, name: "Big Brother", type: "head" },
    { id: 15, name: "Bone Daddy", type: "head" },
    { id: 16, name: "Boss", type: "head" },
    { id: 17, name: "Bowling", type: "head" },
    { id: 18, name: "Bubblegum", type: "head" },
    { id: 19, name: "Bumblebee", type: "head" },
    { id: 20, name: "Business", type: "head" },
    { id: 21, name: "Butane", type: "head" },
    { id: 22, name: "Cadillac", type: "head" },
    { id: 23, name: "Camo", type: "head" },
    { id: 24, name: "China", type: "head" },
    { id: 25, name: "Classic", type: "head" },
    { id: 26, name: "Coin", type: "head" },
    { id: 27, name: "Corroded", type: "head" },
    { id: 28, name: "Cotton Candy", type: "head" },
    { id: 29, name: "Cream", type: "head" },
    { id: 30, name: "Crimson", type: "head" },
    { id: 31, name: "Dazed Piggy", type: "head" },
    { id: 32, name: "Derelict", type: "head" },
    { id: 33, name: "Disco", type: "head" },
    { id: 34, name: "Discomania", type: "head" },
    { id: 35, name: "Dragonfly", type: "head" },
    { id: 36, name: "Shamrock", type: "head" },
    { id: 37, name: "Dualtone", type: "head" },
    { id: 38, name: "Electrik", type: "head" },
    { id: 39, name: "Ellie Mesh", type: "head" },
    { id: 40, name: "Exposed", type: "head" },
    { id: 41, name: "Flaked", type: "head" },
    { id: 42, name: "Frost King", type: "head" },
    { id: 43, name: "Gold", type: "head" },
    { id: 44, name: "Grass", type: "head" },
    { id: 45, name: "Hacker", type: "head" },
    { id: 46, name: "Hades", type: "head" },
    { id: 47, name: "Hal", type: "head" },
    { id: 48, name: "Heatmap", type: "head" },
    { id: 49, name: "Ivory", type: "head" },
    { id: 50, name: "Kevlar", type: "head" },
    { id: 51, name: "Lazer", type: "head" },
    { id: 52, name: "Nightstalker", type: "head" },
    { id: 53, name: "Nyan", type: "head" },
    { id: 54, name: "Nyan Ultimate", type: "head" },
    { id: 55, name: "Obliterator", type: "head" },
    { id: 56, name: "Paul", type: "head" },
    { id: 57, name: "Paul Ultimate", type: "head" },
    { id: 58, name: "Pie", type: "head" },
    { id: 59, name: "Pizza", type: "head" },
    { id: 60, name: "Plate", type: "head" },
    { id: 61, name: "Projectionist", type: "head" },
    { id: 62, name: "Ross", type: "head" },
    { id: 63, name: "Silicon", type: "head" },
    { id: 64, name: "Snow", type: "head" },
    { id: 65, name: "Stained Glass", type: "head" },
    { id: 66, name: "Terminator", type: "head" },
    { id: 67, name: "The Lethal Dimension", type: "head" },
    { id: 68, name: "Drill", type: "head" },
    { id: 69, name: "Lich", type: "head" },
    { id: 70, name: "Lightning", type: "head" },
    { id: 71, name: "Liquid Lavender", type: "head" },
    { id: 72, name: "Log", type: "head" },
    { id: 73, name: "Mac & Cheese", type: "head" },
    { id: 74, name: "Magma", type: "head" },
    { id: 75, name: "Mahogany", type: "head" },
    { id: 76, name: "Mars Attacks", type: "head" },
    { id: 77, name: "Mesh", type: "head" },
    { id: 78, name: "Milk", type: "head" },
    { id: 79, name: "Mint", type: "head" },
    { id: 80, name: "Neon Flamingo", type: "head" },
    { id: 81, name: "Nuke", type: "head" },
    { id: 82, name: "Ol' Faithful", type: "head" },
    { id: 83, name: "Ornament", type: "head" },
    { id: 84, name: "Plastik", type: "head" },
    { id: 85, name: "Polished", type: "head" },
    { id: 86, name: "Porcelain", type: "head" },
    { id: 87, name: "Quilt", type: "head" },
    { id: 88, name: "Recon", type: "head" },
    { id: 89, name: "Royal", type: "head" },
    { id: 90, name: "Rust", type: "head" },
    { id: 91, name: "Sahara", type: "head" },
    { id: 92, name: "Silent Film", type: "head" },
    { id: 93, name: "Sleet", type: "head" },
    { id: 94, name: "Snapshot", type: "head" },
    { id: 95, name: "Sterling", type: "head" },
    { id: 96, name: "Sun", type: "head" },
    { id: 97, name: "Taser", type: "head" },
    { id: 98, name: "The Ram", type: "head" },
    { id: 99, name: "Tron", type: "head" },
    { id: 100, name: "Whiskey", type: "head" },
    { id: 101, name: "Wires", type: "head" },
    { id: 102, name: "desufnoC", type: "head" }
  ],

  // BODY VARIATIONS (103-214)
  bodies: [
    { id: 103, name: "007", type: "body" },
    { id: 104, name: "Abominable", type: "body" },
    { id: 105, name: "Arctic", type: "body" },
    { id: 106, name: "Aztec", type: "body" },
    { id: 107, name: "Bag", type: "body" },
    { id: 108, name: "Black", type: "body" },
    { id: 109, name: "Blood", type: "body" },
    { id: 110, name: "Blush", type: "body" },
    { id: 111, name: "Bone", type: "body" },
    { id: 112, name: "Burnt", type: "body" },
    { id: 113, name: "Burnt Ultimate", type: "body" },
    { id: 114, name: "Carbon", type: "body" },
    { id: 115, name: "Cartoon", type: "body" },
    { id: 116, name: "Cartoonichrome", type: "body" },
    { id: 117, name: "Carving", type: "body" },
    { id: 118, name: "Carving Ultimate", type: "body" },
    { id: 119, name: "Cheetah", type: "body" },
    { id: 120, name: "Chrome", type: "body" },
    { id: 121, name: "Chrome Ultimate", type: "body" },
    { id: 122, name: "Couch", type: "body" },
    { id: 123, name: "Cousin Itt", type: "body" },
    { id: 124, name: "Crystal Camo", type: "body" },
    { id: 125, name: "Crystal Clear", type: "body" },
    { id: 126, name: "Cubes", type: "body" },
    { id: 127, name: "Damascus", type: "body" },
    { id: 128, name: "Denim", type: "body" },
    { id: 129, name: "Doom", type: "body" },
    { id: 130, name: "Dr.", type: "body" },
    { id: 131, name: "Eyes", type: "body" },
    { id: 132, name: "Forest", type: "body" },
    { id: 133, name: "Frost Cage", type: "body" },
    { id: 134, name: "Frostbit", type: "body" },
    { id: 135, name: "Frosted", type: "body" },
    { id: 136, name: "Fury", type: "body" },
    { id: 137, name: "Gatsby", type: "body" },
    { id: 138, name: "Gatsby Ultimate", type: "body" },
    { id: 139, name: "Giger", type: "body" },
    { id: 140, name: "Goblin", type: "body" },
    { id: 141, name: "Granite", type: "body" },
    { id: 142, name: "Grate", type: "body" },
    { id: 143, name: "Happymeal", type: "body" },
    { id: 144, name: "Heart", type: "body" },
    { id: 145, name: "Heatwave", type: "body" },
    { id: 146, name: "Heatwave Ultimate", type: "body" },
    { id: 147, name: "Highlights", type: "body" },
    { id: 148, name: "Inner Rainbow", type: "body" },
    { id: 149, name: "Iron", type: "body" },
    { id: 150, name: "James", type: "body" },
    { id: 151, name: "Jolly Rancher", type: "body" },
    { id: 152, name: "Journey", type: "body" },
    { id: 153, name: "Leeloo", type: "body" },
    { id: 154, name: "Lizard", type: "body" },
    { id: 155, name: "Lord", type: "body" },
    { id: 156, name: "Luxury", type: "body" },
    { id: 157, name: "Luxury Ultimate", type: "body" },
    { id: 158, name: "Majesty", type: "body" },
    { id: 159, name: "Maple", type: "body" },
    { id: 160, name: "Maps", type: "body" },  // The Maps variation you were looking for!
    { id: 161, name: "Marble", type: "body" },
    { id: 162, name: "Matte", type: "body" },
    { id: 163, name: "Maze", type: "body" },
    { id: 164, name: "Meat", type: "body" },
    { id: 165, name: "Mercury", type: "body" },
    { id: 166, name: "Mugged", type: "body" },
    { id: 167, name: "Noob", type: "body" },
    { id: 168, name: "Nuggets", type: "body" },
    { id: 169, name: "OE Dark", type: "body" },
    { id: 170, name: "OE Light", type: "body" },
    { id: 171, name: "Obsidian", type: "body" },
    { id: 172, name: "Ocean", type: "body" },
    { id: 173, name: "Oil", type: "body" },
    { id: 174, name: "Ooze", type: "body" },
    { id: 175, name: "Pearl", type: "body" },
    { id: 176, name: "Peppermint", type: "body" },
    { id: 177, name: "Plush", type: "body" },
    { id: 178, name: "Plush Ultimate", type: "body" },
    { id: 179, name: "Poker", type: "body" },
    { id: 180, name: "Prickles", type: "body" },
    { id: 181, name: "Princess", type: "body" },
    { id: 182, name: "Prom", type: "body" },
    { id: 183, name: "Radiance", type: "body" },
    { id: 184, name: "Rattler", type: "body" },
    { id: 185, name: "Rose", type: "body" },
    { id: 186, name: "Rug", type: "body" },
    { id: 187, name: "Rust", type: "body" },
    { id: 188, name: "Sand", type: "body" },
    { id: 189, name: "Seabiscuit", type: "body" },
    { id: 190, name: "Seafoam", type: "body" },
    { id: 191, name: "Shipped", type: "body" },
    { id: 192, name: "Sir", type: "body" },
    { id: 193, name: "Sky", type: "body" },
    { id: 194, name: "Smurf", type: "body" },
    { id: 195, name: "Soul", type: "body" },
    { id: 196, name: "Spaghetti", type: "body" },
    { id: 197, name: "Stars", type: "body" },
    { id: 198, name: "Steam", type: "body" },
    { id: 199, name: "Sticky", type: "body" },
    { id: 200, name: "Stone", type: "body" },
    { id: 201, name: "Sunset", type: "body" },
    { id: 202, name: "Tangerine", type: "body" },
    { id: 203, name: "Tarpie", type: "body" },
    { id: 204, name: "Tat", type: "body" },
    { id: 205, name: "Tickle", type: "body" },
    { id: 206, name: "Tie Dye", type: "body" },
    { id: 207, name: "Tiles", type: "body" },
    { id: 208, name: "Trapped", type: "body" },
    { id: 209, name: "Vapor", type: "body" },
    { id: 210, name: "Victoria", type: "body" },
    { id: 211, name: "Waves", type: "body" },
    { id: 212, name: "White", type: "body" },
    { id: 213, name: "X Ray", type: "body" },
    { id: 214, name: "X Ray Ultimate", type: "body" },
  ],

  // ITEM VARIATIONS (215-291) - All 77 items
  items: [
    { id: 215, name: "101.1 FM", type: "item" },
    { id: 216, name: "2001", type: "item" },
    { id: 217, name: "Albino", type: "item" },
    { id: 218, name: "Angler", type: "item" },
    { id: 219, name: "Black & White", type: "item" },
    { id: 220, name: "Black Parade", type: "item" },
    { id: 221, name: "Blasters", type: "item" },
    { id: 222, name: "Bling", type: "item" },
    { id: 223, name: "Bonebox", type: "item" },
    { id: 224, name: "Bumble Bird", type: "item" },
    { id: 225, name: "Carbonite", type: "item" },
    { id: 226, name: "Chromium", type: "item" },
    { id: 227, name: "Concrete", type: "item" },
    { id: 228, name: "Contractor", type: "item" },
    { id: 229, name: "Crow", type: "item" },
    { id: 230, name: "Deep Space", type: "item" },
    { id: 231, name: "Drip", type: "item" },
    { id: 232, name: "Earth", type: "item" },
    { id: 233, name: "Firebird", type: "item" },
    { id: 234, name: "Foil", type: "item" },
    { id: 235, name: "Fourzin", type: "item" },
    { id: 236, name: "Golden Guns", type: "item" },
    { id: 237, name: "Golden Guns Ultimate", type: "item" },
    { id: 238, name: "Gone", type: "item" },
    { id: 239, name: "Hammerheat", type: "item" },
    { id: 240, name: "Hefner", type: "item" },
    { id: 241, name: "Heliotropium", type: "item" },
    { id: 242, name: "Holographic", type: "item" },
    { id: 243, name: "Hydra", type: "item" },
    { id: 244, name: "Iced", type: "item" },
    { id: 245, name: "Icon", type: "item" },
    { id: 246, name: "Jeff", type: "item" },
    { id: 247, name: "Just Wren", type: "item" },
    { id: 248, name: "King Tut", type: "item" },
    { id: 249, name: "LV-426", type: "item" },
    { id: 250, name: "Linkinator 3000", type: "item" },
    { id: 251, name: "Lumberjack", type: "item" },
    { id: 252, name: "Luna", type: "item" },
    { id: 253, name: "Molten Core", type: "item" },
    { id: 254, name: "Moth", type: "item" },
    { id: 255, name: "Near Space", type: "item" },
    { id: 256, name: "Night Vision", type: "item" },
    { id: 257, name: "Nil", type: "item" },
    { id: 258, name: "None", type: "item" },
    { id: 259, name: "Nothing", type: "item" },
    { id: 260, name: "Nuclear", type: "item" },
    { id: 261, name: "Null", type: "item" },
    { id: 262, name: "Oompah", type: "item" },
    { id: 263, name: "Palace", type: "item" },
    { id: 264, name: "Paparazzi", type: "item" },
    { id: 265, name: "Pawn Shop", type: "item" },
    { id: 266, name: "Peacock", type: "item" },
    { id: 267, name: "Peacock Ultimate", type: "item" },
    { id: 268, name: "Phoenix", type: "item" },
    { id: 269, name: "Pop", type: "item" },
    { id: 270, name: "Purplex", type: "item" },
    { id: 271, name: "Pyrex", type: "item" },
    { id: 272, name: "R&B", type: "item" },
    { id: 273, name: "Rainbow Morpho", type: "item" },
    { id: 274, name: "Ring Blue", type: "item" },
    { id: 275, name: "Ring Green", type: "item" },
    { id: 276, name: "Ring Red", type: "item" },
    { id: 277, name: "Sap", type: "item" },
    { id: 278, name: "Scissors", type: "item" },
    { id: 279, name: "Screamo", type: "item" },
    { id: 280, name: "Silver", type: "item" },
    { id: 281, name: "Spectrum", type: "item" },
    { id: 282, name: "Splatter", type: "item" },
    { id: 283, name: "Stock", type: "item" },
    { id: 284, name: "Stolen", type: "item" },
    { id: 285, name: "Tactical", type: "item" },
    { id: 286, name: "Technicolor", type: "item" },
    { id: 287, name: "Test Track", type: "item" },
    { id: 288, name: "Vampire", type: "item" },
    { id: 289, name: "Vanished", type: "item" },
    { id: 290, name: "Whiteout", type: "item" },
    { id: 291, name: "Who", type: "item" },
  ]
};

// Create a flattened map for easy lookup
export const VARIATION_MAP = new Map<number, { id: number; name: string; type: string }>();
[...ALL_VARIATIONS.heads, ...ALL_VARIATIONS.bodies, ...ALL_VARIATIONS.items].forEach(v => {
  VARIATION_MAP.set(v.id, v);
});

// Add variations reference to database
export const seedVariationsReference = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("variationsReference").first();
    if (existing) {
      return { message: "Variations reference already exists" };
    }

    // Insert all variations
    const allVariations = [
      ...ALL_VARIATIONS.heads,
      ...ALL_VARIATIONS.bodies,
      ...ALL_VARIATIONS.items
    ];

    for (const variation of allVariations) {
      await ctx.db.insert("variationsReference", {
        variationId: variation.id,
        name: variation.name,
        type: variation.type as "head" | "body" | "item",
        baseXp: 100, // Default XP value
      });
    }

    return {
      message: `Seeded ${allVariations.length} variations`,
      heads: ALL_VARIATIONS.heads.length,
      bodies: ALL_VARIATIONS.bodies.length,
      items: ALL_VARIATIONS.items.length,
    };
  },
});

// Query to get variation by ID
export const getVariationById = query({
  args: { variationId: v.number() },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("variationsReference")
      .filter(q => q.eq(q.field("variationId"), args.variationId))
      .first();
  },
});

// Query to get all variations by type
export const getVariationsByType = query({
  args: { type: v.union(v.literal("head"), v.literal("body"), v.literal("item")) },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("variationsReference")
      .filter(q => q.eq(q.field("type"), args.type))
      .collect();
  },
});