/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accordionCraftingTree from "../accordionCraftingTree.js";
import type * as actions_verifyCardanoSignature from "../actions/verifyCardanoSignature.js";
import type * as actions_verifyCardanoSignatureSimple from "../actions/verifyCardanoSignatureSimple.js";
import type * as activeMissions from "../activeMissions.js";
import type * as activityLogs from "../activityLogs.js";
import type * as addTotalActiveContracts from "../addTotalActiveContracts.js";
import type * as addressConversion from "../addressConversion.js";
import type * as adminEssence from "../adminEssence.js";
import type * as adminGoldInvestigation from "../adminGoldInvestigation.js";
import type * as adminMarketplace from "../adminMarketplace.js";
import type * as adminMigration from "../adminMigration.js";
import type * as adminResetAllProgress from "../adminResetAllProgress.js";
import type * as adminSyncFix from "../adminSyncFix.js";
import type * as adminUsers from "../adminUsers.js";
import type * as adminVerificationReset from "../adminVerificationReset.js";
import type * as airdrop from "../airdrop.js";
import type * as attributeRarity from "../attributeRarity.js";
import type * as attributeRarityManual from "../attributeRarityManual.js";
import type * as auditLogs from "../auditLogs.js";
import type * as bank from "../bank.js";
import type * as blockchainVerification from "../blockchainVerification.js";
import type * as blockchainVerificationRefactored from "../blockchainVerificationRefactored.js";
import type * as blockfrostConfig from "../blockfrostConfig.js";
import type * as blockfrostNftFetcher from "../blockfrostNftFetcher.js";
import type * as blockfrostService from "../blockfrostService.js";
import type * as buffCategories from "../buffCategories.js";
import type * as buffManager from "../buffManager.js";
import type * as buffs from "../buffs.js";
import type * as chipConfigurations from "../chipConfigurations.js";
import type * as chips from "../chips.js";
import type * as cleanupDifficultyConfigs from "../cleanupDifficultyConfigs.js";
import type * as commemorative from "../commemorative.js";
import type * as comprehensiveWalletFix from "../comprehensiveWalletFix.js";
import type * as contracts from "../contracts.js";
import type * as crafting from "../crafting.js";
import type * as crons from "../crons.js";
import type * as debugAllConnections from "../debugAllConnections.js";
import type * as debugDiscordConnection from "../debugDiscordConnection.js";
import type * as debugGold from "../debugGold.js";
import type * as debugGoldDisplay from "../debugGoldDisplay.js";
import type * as debugGoldInvariants from "../debugGoldInvariants.js";
import type * as debugLeaderboard from "../debugLeaderboard.js";
import type * as debugLeaderboardCache from "../debugLeaderboardCache.js";
import type * as debugMekLevels from "../debugMekLevels.js";
import type * as debugSnapshotData from "../debugSnapshotData.js";
import type * as debugWalletData from "../debugWalletData.js";
import type * as debugWalletSnapshot from "../debugWalletSnapshot.js";
import type * as definitiveWalletFix from "../definitiveWalletFix.js";
import type * as deleteMockAccounts from "../deleteMockAccounts.js";
import type * as deleteZeroMekAccounts from "../deleteZeroMekAccounts.js";
import type * as deployedNodeData from "../deployedNodeData.js";
import type * as devToolbar from "../devToolbar.js";
import type * as diagnosticBlockfrostUsage from "../diagnosticBlockfrostUsage.js";
import type * as diagnosticCorruptedGold from "../diagnosticCorruptedGold.js";
import type * as diagnosticDiscordConnections from "../diagnosticDiscordConnections.js";
import type * as diagnosticDiscordData from "../diagnosticDiscordData.js";
import type * as diagnosticMekBoosts from "../diagnosticMekBoosts.js";
import type * as diagnosticRequestAnalysis from "../diagnosticRequestAnalysis.js";
import type * as diagnosticWalletCheck from "../diagnosticWalletCheck.js";
import type * as diagnosticWalletHistory from "../diagnosticWalletHistory.js";
import type * as difficultyConfigs from "../difficultyConfigs.js";
import type * as discordIntegration from "../discordIntegration.js";
import type * as discordIntegrationGroups from "../discordIntegrationGroups.js";
import type * as discordSync from "../discordSync.js";
import type * as discordTodos from "../discordTodos.js";
import type * as duplicateWalletDetection from "../duplicateWalletDetection.js";
import type * as durationConfigs from "../durationConfigs.js";
import type * as essence from "../essence.js";
import type * as eventNodeRewards from "../eventNodeRewards.js";
import type * as federations from "../federations.js";
import type * as files from "../files.js";
import type * as finalDuplicateCleanup from "../finalDuplicateCleanup.js";
import type * as finalWalletFix from "../finalWalletFix.js";
import type * as fixBadSnapshots from "../fixBadSnapshots.js";
import type * as fixCorruptedGold from "../fixCorruptedGold.js";
import type * as fixDiscordGroupData from "../fixDiscordGroupData.js";
import type * as fixGoldRateCalculation from "../fixGoldRateCalculation.js";
import type * as fixMek3412To000 from "../fixMek3412To000.js";
import type * as fixWalletDuplicates from "../fixWalletDuplicates.js";
import type * as fixWalletSnapshot from "../fixWalletSnapshot.js";
import type * as gameConfigs from "../gameConfigs.js";
import type * as gameConstants from "../gameConstants.js";
import type * as gameItemsSearch from "../gameItemsSearch.js";
import type * as getAllMekHolders from "../getAllMekHolders.js";
import type * as getAllSourceKeys from "../getAllSourceKeys.js";
import type * as getTop50MekHolders from "../getTop50MekHolders.js";
import type * as getWalletAssetsFlexible from "../getWalletAssetsFlexible.js";
import type * as goldBackupScheduler from "../goldBackupScheduler.js";
import type * as goldBackups from "../goldBackups.js";
import type * as goldCheckpointing from "../goldCheckpointing.js";
import type * as goldCheckpointingActions from "../goldCheckpointingActions.js";
import type * as goldLeaderboard from "../goldLeaderboard.js";
import type * as goldMining from "../goldMining.js";
import type * as goldMiningSnapshot from "../goldMiningSnapshot.js";
import type * as goldTracking from "../goldTracking.js";
import type * as goldTrackingOptimized from "../goldTrackingOptimized.js";
import type * as importFullMekCollection from "../importFullMekCollection.js";
import type * as initializeCache from "../initializeCache.js";
import type * as investments from "../investments.js";
import type * as leaderboard from "../leaderboard.js";
import type * as leaderboardDiagnostics from "../leaderboardDiagnostics.js";
import type * as leaderboardOptimized from "../leaderboardOptimized.js";
import type * as leaderboardUpdater from "../leaderboardUpdater.js";
import type * as levelColors from "../levelColors.js";
import type * as lib_devLog from "../lib/devLog.js";
import type * as lib_goldCalculations from "../lib/goldCalculations.js";
import type * as lib_nftFetchingService from "../lib/nftFetchingService.js";
import type * as lib_sessionUtils from "../lib/sessionUtils.js";
import type * as lib_verificationService from "../lib/verificationService.js";
import type * as listAllGoldMiningAccounts from "../listAllGoldMiningAccounts.js";
import type * as loans from "../loans.js";
import type * as manualWalletMerge from "../manualWalletMerge.js";
import type * as marketplace from "../marketplace.js";
import type * as mechanismTiers from "../mechanismTiers.js";
import type * as mekGoldRates from "../mekGoldRates.js";
import type * as mekLeveling from "../mekLeveling.js";
import type * as mekSuccessRates from "../mekSuccessRates.js";
import type * as mekTalentTrees from "../mekTalentTrees.js";
import type * as mekTreeBuffTables from "../mekTreeBuffTables.js";
import type * as mekTreeTableSaves from "../mekTreeTableSaves.js";
import type * as mekTreeTables from "../mekTreeTables.js";
import type * as mekTreeTemplates from "../mekTreeTemplates.js";
import type * as meks from "../meks.js";
import type * as metadataResolution from "../metadataResolution.js";
import type * as migrateBuffCategories from "../migrateBuffCategories.js";
import type * as migrateMultiWallet from "../migrateMultiWallet.js";
import type * as migrationUtils from "../migrationUtils.js";
import type * as migrations from "../migrations.js";
import type * as mintHistory from "../mintHistory.js";
import type * as monitoring from "../monitoring.js";
import type * as monitoringSummaryGenerator from "../monitoringSummaryGenerator.js";
import type * as multiWalletAggregation from "../multiWalletAggregation.js";
import type * as nftArtAssets from "../nftArtAssets.js";
import type * as nftEvents from "../nftEvents.js";
import type * as nftPurchases from "../nftPurchases.js";
import type * as nftSyncSaga from "../nftSyncSaga.js";
import type * as nftVariations from "../nftVariations.js";
import type * as nmkrApi from "../nmkrApi.js";
import type * as nmkrSync from "../nmkrSync.js";
import type * as nodeFeeVersions from "../nodeFeeVersions.js";
import type * as nodeFees from "../nodeFees.js";
import type * as normalMekRewards from "../normalMekRewards.js";
import type * as offlineAccumulation from "../offlineAccumulation.js";
import type * as optimizedQueries from "../optimizedQueries.js";
import type * as overlays from "../overlays.js";
import type * as publicCorporation from "../publicCorporation.js";
import type * as runStoryClimbMigration from "../runStoryClimbMigration.js";
import type * as saves from "../saves.js";
import type * as securityMonitoring from "../securityMonitoring.js";
import type * as seedBuffCategories from "../seedBuffCategories.js";
import type * as seedData from "../seedData.js";
import type * as seedMarketplace from "../seedMarketplace.js";
import type * as seedMeks from "../seedMeks.js";
import type * as seedShopListings from "../seedShopListings.js";
import type * as sessionManagement from "../sessionManagement.js";
import type * as smartContractArchitecture from "../smartContractArchitecture.js";
import type * as snapshotCleanup from "../snapshotCleanup.js";
import type * as snapshotHealthCheck from "../snapshotHealthCheck.js";
import type * as snapshotHistory from "../snapshotHistory.js";
import type * as spells from "../spells.js";
import type * as stocks from "../stocks.js";
import type * as storageMonitoring from "../storageMonitoring.js";
import type * as storyClimbOptimized from "../storyClimbOptimized.js";
import type * as storyNodes from "../storyNodes.js";
import type * as storyTrees from "../storyTrees.js";
import type * as sunspotActions from "../sunspotActions.js";
import type * as sunspotAntiCheat from "../sunspotAntiCheat.js";
import type * as sunspots from "../sunspots.js";
import type * as syncChecksums from "../syncChecksums.js";
import type * as talentTree from "../talentTree.js";
import type * as testSessionManagement from "../testSessionManagement.js";
import type * as transactionCleanup from "../transactionCleanup.js";
import type * as updateVariationImages from "../updateVariationImages.js";
import type * as userStats from "../userStats.js";
import type * as usernames from "../usernames.js";
import type * as users from "../users.js";
import type * as validateGoldInvariants from "../validateGoldInvariants.js";
import type * as variationBuffs from "../variationBuffs.js";
import type * as variations from "../variations.js";
import type * as variationsReference from "../variationsReference.js";
import type * as walletAuth from "../walletAuth.js";
import type * as walletAuthentication from "../walletAuthentication.js";
import type * as walletGroups from "../walletGroups.js";
import type * as walletSession from "../walletSession.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  accordionCraftingTree: typeof accordionCraftingTree;
  "actions/verifyCardanoSignature": typeof actions_verifyCardanoSignature;
  "actions/verifyCardanoSignatureSimple": typeof actions_verifyCardanoSignatureSimple;
  activeMissions: typeof activeMissions;
  activityLogs: typeof activityLogs;
  addTotalActiveContracts: typeof addTotalActiveContracts;
  addressConversion: typeof addressConversion;
  adminEssence: typeof adminEssence;
  adminGoldInvestigation: typeof adminGoldInvestigation;
  adminMarketplace: typeof adminMarketplace;
  adminMigration: typeof adminMigration;
  adminResetAllProgress: typeof adminResetAllProgress;
  adminSyncFix: typeof adminSyncFix;
  adminUsers: typeof adminUsers;
  adminVerificationReset: typeof adminVerificationReset;
  airdrop: typeof airdrop;
  attributeRarity: typeof attributeRarity;
  attributeRarityManual: typeof attributeRarityManual;
  auditLogs: typeof auditLogs;
  bank: typeof bank;
  blockchainVerification: typeof blockchainVerification;
  blockchainVerificationRefactored: typeof blockchainVerificationRefactored;
  blockfrostConfig: typeof blockfrostConfig;
  blockfrostNftFetcher: typeof blockfrostNftFetcher;
  blockfrostService: typeof blockfrostService;
  buffCategories: typeof buffCategories;
  buffManager: typeof buffManager;
  buffs: typeof buffs;
  chipConfigurations: typeof chipConfigurations;
  chips: typeof chips;
  cleanupDifficultyConfigs: typeof cleanupDifficultyConfigs;
  commemorative: typeof commemorative;
  comprehensiveWalletFix: typeof comprehensiveWalletFix;
  contracts: typeof contracts;
  crafting: typeof crafting;
  crons: typeof crons;
  debugAllConnections: typeof debugAllConnections;
  debugDiscordConnection: typeof debugDiscordConnection;
  debugGold: typeof debugGold;
  debugGoldDisplay: typeof debugGoldDisplay;
  debugGoldInvariants: typeof debugGoldInvariants;
  debugLeaderboard: typeof debugLeaderboard;
  debugLeaderboardCache: typeof debugLeaderboardCache;
  debugMekLevels: typeof debugMekLevels;
  debugSnapshotData: typeof debugSnapshotData;
  debugWalletData: typeof debugWalletData;
  debugWalletSnapshot: typeof debugWalletSnapshot;
  definitiveWalletFix: typeof definitiveWalletFix;
  deleteMockAccounts: typeof deleteMockAccounts;
  deleteZeroMekAccounts: typeof deleteZeroMekAccounts;
  deployedNodeData: typeof deployedNodeData;
  devToolbar: typeof devToolbar;
  diagnosticBlockfrostUsage: typeof diagnosticBlockfrostUsage;
  diagnosticCorruptedGold: typeof diagnosticCorruptedGold;
  diagnosticDiscordConnections: typeof diagnosticDiscordConnections;
  diagnosticDiscordData: typeof diagnosticDiscordData;
  diagnosticMekBoosts: typeof diagnosticMekBoosts;
  diagnosticRequestAnalysis: typeof diagnosticRequestAnalysis;
  diagnosticWalletCheck: typeof diagnosticWalletCheck;
  diagnosticWalletHistory: typeof diagnosticWalletHistory;
  difficultyConfigs: typeof difficultyConfigs;
  discordIntegration: typeof discordIntegration;
  discordIntegrationGroups: typeof discordIntegrationGroups;
  discordSync: typeof discordSync;
  discordTodos: typeof discordTodos;
  duplicateWalletDetection: typeof duplicateWalletDetection;
  durationConfigs: typeof durationConfigs;
  essence: typeof essence;
  eventNodeRewards: typeof eventNodeRewards;
  federations: typeof federations;
  files: typeof files;
  finalDuplicateCleanup: typeof finalDuplicateCleanup;
  finalWalletFix: typeof finalWalletFix;
  fixBadSnapshots: typeof fixBadSnapshots;
  fixCorruptedGold: typeof fixCorruptedGold;
  fixDiscordGroupData: typeof fixDiscordGroupData;
  fixGoldRateCalculation: typeof fixGoldRateCalculation;
  fixMek3412To000: typeof fixMek3412To000;
  fixWalletDuplicates: typeof fixWalletDuplicates;
  fixWalletSnapshot: typeof fixWalletSnapshot;
  gameConfigs: typeof gameConfigs;
  gameConstants: typeof gameConstants;
  gameItemsSearch: typeof gameItemsSearch;
  getAllMekHolders: typeof getAllMekHolders;
  getAllSourceKeys: typeof getAllSourceKeys;
  getTop50MekHolders: typeof getTop50MekHolders;
  getWalletAssetsFlexible: typeof getWalletAssetsFlexible;
  goldBackupScheduler: typeof goldBackupScheduler;
  goldBackups: typeof goldBackups;
  goldCheckpointing: typeof goldCheckpointing;
  goldCheckpointingActions: typeof goldCheckpointingActions;
  goldLeaderboard: typeof goldLeaderboard;
  goldMining: typeof goldMining;
  goldMiningSnapshot: typeof goldMiningSnapshot;
  goldTracking: typeof goldTracking;
  goldTrackingOptimized: typeof goldTrackingOptimized;
  importFullMekCollection: typeof importFullMekCollection;
  initializeCache: typeof initializeCache;
  investments: typeof investments;
  leaderboard: typeof leaderboard;
  leaderboardDiagnostics: typeof leaderboardDiagnostics;
  leaderboardOptimized: typeof leaderboardOptimized;
  leaderboardUpdater: typeof leaderboardUpdater;
  levelColors: typeof levelColors;
  "lib/devLog": typeof lib_devLog;
  "lib/goldCalculations": typeof lib_goldCalculations;
  "lib/nftFetchingService": typeof lib_nftFetchingService;
  "lib/sessionUtils": typeof lib_sessionUtils;
  "lib/verificationService": typeof lib_verificationService;
  listAllGoldMiningAccounts: typeof listAllGoldMiningAccounts;
  loans: typeof loans;
  manualWalletMerge: typeof manualWalletMerge;
  marketplace: typeof marketplace;
  mechanismTiers: typeof mechanismTiers;
  mekGoldRates: typeof mekGoldRates;
  mekLeveling: typeof mekLeveling;
  mekSuccessRates: typeof mekSuccessRates;
  mekTalentTrees: typeof mekTalentTrees;
  mekTreeBuffTables: typeof mekTreeBuffTables;
  mekTreeTableSaves: typeof mekTreeTableSaves;
  mekTreeTables: typeof mekTreeTables;
  mekTreeTemplates: typeof mekTreeTemplates;
  meks: typeof meks;
  metadataResolution: typeof metadataResolution;
  migrateBuffCategories: typeof migrateBuffCategories;
  migrateMultiWallet: typeof migrateMultiWallet;
  migrationUtils: typeof migrationUtils;
  migrations: typeof migrations;
  mintHistory: typeof mintHistory;
  monitoring: typeof monitoring;
  monitoringSummaryGenerator: typeof monitoringSummaryGenerator;
  multiWalletAggregation: typeof multiWalletAggregation;
  nftArtAssets: typeof nftArtAssets;
  nftEvents: typeof nftEvents;
  nftPurchases: typeof nftPurchases;
  nftSyncSaga: typeof nftSyncSaga;
  nftVariations: typeof nftVariations;
  nmkrApi: typeof nmkrApi;
  nmkrSync: typeof nmkrSync;
  nodeFeeVersions: typeof nodeFeeVersions;
  nodeFees: typeof nodeFees;
  normalMekRewards: typeof normalMekRewards;
  offlineAccumulation: typeof offlineAccumulation;
  optimizedQueries: typeof optimizedQueries;
  overlays: typeof overlays;
  publicCorporation: typeof publicCorporation;
  runStoryClimbMigration: typeof runStoryClimbMigration;
  saves: typeof saves;
  securityMonitoring: typeof securityMonitoring;
  seedBuffCategories: typeof seedBuffCategories;
  seedData: typeof seedData;
  seedMarketplace: typeof seedMarketplace;
  seedMeks: typeof seedMeks;
  seedShopListings: typeof seedShopListings;
  sessionManagement: typeof sessionManagement;
  smartContractArchitecture: typeof smartContractArchitecture;
  snapshotCleanup: typeof snapshotCleanup;
  snapshotHealthCheck: typeof snapshotHealthCheck;
  snapshotHistory: typeof snapshotHistory;
  spells: typeof spells;
  stocks: typeof stocks;
  storageMonitoring: typeof storageMonitoring;
  storyClimbOptimized: typeof storyClimbOptimized;
  storyNodes: typeof storyNodes;
  storyTrees: typeof storyTrees;
  sunspotActions: typeof sunspotActions;
  sunspotAntiCheat: typeof sunspotAntiCheat;
  sunspots: typeof sunspots;
  syncChecksums: typeof syncChecksums;
  talentTree: typeof talentTree;
  testSessionManagement: typeof testSessionManagement;
  transactionCleanup: typeof transactionCleanup;
  updateVariationImages: typeof updateVariationImages;
  userStats: typeof userStats;
  usernames: typeof usernames;
  users: typeof users;
  validateGoldInvariants: typeof validateGoldInvariants;
  variationBuffs: typeof variationBuffs;
  variations: typeof variations;
  variationsReference: typeof variationsReference;
  walletAuth: typeof walletAuth;
  walletAuthentication: typeof walletAuthentication;
  walletGroups: typeof walletGroups;
  walletSession: typeof walletSession;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
