import { v } from "convex/values";
import { mutation } from "./_generated/server";

// Map of variation names to their image files
// This list is based on the files in public/variation-images/
const VARIATION_IMAGE_MAP: Record<string, string> = {
  "007": "007.png",
  "101.1 FM": "101.1_fm.png",
  "1960s": "1960s.png",
  "2001": "2001.png",
  "24K": "24k.png",
  "Abominable": "abominable.png",
  "Ace of Spades": "ace_of_spades.png",
  "Ace of Spades Ultima": "ace_of_spades_ultima.png",
  "Ace of Spades Ultimate": "ace_of_spades_ultimate.png",
  "Acid": "acid.png",
  "Acrylic": "acrylic.png",
  "Albino": "albino.png",
  "Angler": "angler.png",
  "Aqua": "aqua.png",
  "Arcade": "arcade.png",
  "Arctic": "arctic.png",
  "Aztec": "aztec.png",
  "Baby": "baby.png",
  "Bag": "bag.png",
  "Ballerina": "ballerina.png",
  "Bark": "bark.png",
  "Big Brother": "big_brother.png",
  "Black": "black.png",
  "Black & White": "black_&_white.png",
  "Black Parade": "black_parade.png",
  "Blasters": "blasters.png",
  "Bling": "bling.png",
  "Blood": "blood.png",
  "Blush": "blush.png",
  "Bone": "bone.png",
  "Bone Daddy": "bone_daddy.png",
  "Bonebox": "bonebox.png",
  "Boombox": "boombox.png",
  "Boss": "boss.png",
  "Bowling": "bowling.png",
  "Broadcast": "broadcast.png",
  "Bubblegum": "bubblegum.png",
  "Bumble Bird": "bumble_bird.png",
  "Bumblebee": "bumblebee.png",
  "Burnt": "burnt.png",
  "Burnt Ultimate": "burnt_ultimate.png",
  "Business": "business.png",
  "Butane": "butane.png",
  "Butterfly": "butterfly.png",
  "Cadillac": "cadillac.png",
  "Camo": "camo.png",
  "Cannon": "cannon.png",
  "Cannon Ultimate": "cannon_ultimate.png",
  "Carbon": "carbon.png",
  "Carbonite": "carbonite.png",
  "Cartoon": "cartoon.png",
  "Cartoonichrome": "cartoonichrome.png",
  "Carving": "carving.png",
  "Carving Ultimate": "carving_ultimate.png",
  "Cheetah": "cheetah.png",
  "China": "china.png",
  "Chrome": "chrome.png",
  "Chrome Ultimate": "chrome_ultimate.png",
  "Chromium": "chromium.png",
  "Classic": "classic.png",
  "Coin": "coin.png",
  "Concrete": "concrete.png",
  "Contractor": "contractor.png",
  "Corroded": "corroded.png",
  "Cotton Candy": "cotton_candy.png",
  "Couch": "couch.png",
  "Cousin Itt": "cousin_itt.png",
  "Cream": "cream.png",
  "Crimson": "crimson.png",
  "Crow": "crow.png",
  "Crystal Camo": "crystal_camo.png",
  "Crystal Clear": "crystal_clear.png",
  "Cubes": "cubes.png",
  "Damascus": "damascus.png",
  "Dazed Piggy": "dazed_piggy.png",
  "Deep Space": "deep_space.png",
  "Denim": "denim.png",
  "Derelict": "derelict.png",
  "Desufnoc": "desufnoc.png",
  "Disco": "disco.png",
  "Discomania": "discomania.png",
  "Doom": "doom.png",
  "Dr.": "dr..png",
  "Dragonfly": "dragonfly.png",
  "Drill": "drill.png",
  "Drip": "drip.png",
  "Dualtone": "dualtone.png",
  "Earth": "earth.png",
  "Electrik": "electrik.png",
  "Ellie Mesh": "ellie_mesh.png",
  "Exposed": "exposed.png",
  "Eyes": "eyes.png",
  "Film": "film.png",
  "Firebird": "firebird.png",
  "Flaked": "flaked.png",
  "Foil": "foil.png",
  "Forest": "forest.png",
  "Fourzin": "fourzin.png",
  "Frost Cage": "frost_cage.png",
  "Frost King": "frost_king.png",
  "Frostbit": "frostbit.png",
  "Frosted": "frosted.png",
  "Fury": "fury.png",
  "Gatsby": "gatsby.png",
  "Gatsby Ultimate": "gatsby_ultimate.png",
  "Giger": "giger.png",
  "Goblin": "goblin.png",
  "Gold": "gold.png",
  "Golden Guns": "golden_guns.png",
  "Golden Guns Ultimate": "golden_guns_ultimate.png",
  "Gone": "gone.png",
  "Granite": "granite.png",
  "Grass": "grass.png",
  "Grate": "grate.png",
  "Hacker": "hacker.png",
  "Hades": "hades.png",
  "Hal": "hal.png",
  "Hammerheat": "hammerheat.png",
  "Happymeal": "happymeal.png",
  "Hawk": "hawk.png",
  "Heart": "heart.png",
  "Heatmap": "heatmap.png",
  "Heatwave": "heatwave.png",
  "Heatwave Ultimate": "heatwave_ultimate.png",
  "Hefner": "hefner.png",
  "Heliotropium": "heliotropium.png",
  "Highlights": "highlights.png",
  "Holographic": "holographic.png",
  "Hydra": "hydra.png",
  "Iced": "iced.png",
  "Icon": "icon.png",
  "Inner Rainbow": "inner_rainbow.png",
  "Iron": "iron.png",
  "Ivory": "ivory.png",
  "James": "james.png",
  "Jeff": "jeff.png",
  "Jolly Rancher": "jolly_rancher.png",
  "Journey": "journey.png",
  "Just Wren": "just_wren.png",
  "Kevlar": "kevlar.png",
  "King Tut": "king_tut.png",
  "Lazer": "lazer.png",
  "Leeloo": "leeloo.png",
  "Lich": "lich.png",
  "Light": "light.png",
  "Lightning": "lightning.png",
  "Linkinator 3000": "linkinator_3000.png",
  "Liquid Lavender": "liquid_lavender.png",
  "Lizard": "lizard.png",
  "Log": "log.png",
  "Lord": "lord.png",
  "Lumberjack": "lumberjack.png",
  "Luna": "luna.png",
  "Luxury": "luxury.png",
  "Luxury Ultimate": "luxury_ultimate.png",
  "LV-426": "lv-426.png",
  "Mac & Cheese": "mac_&_cheese.png",
  "Magma": "magma.png",
  "Mahogany": "mahogany.png",
  "Majesty": "majesty.png",
  "Maple": "maple.png",
  "Maps": "maps.png",
  "Marble": "marble.png",
  "Mars Attacks": "mars_attacks.png",
  "Matte": "matte.png",
  "Maze": "maze.png",
  "Meat": "meat.png",
  "Mercury": "mercury.png",
  "Mesh": "mesh.png",
  "Microphone": "microphone.png",
  "Milk": "milk.png",
  "Mini Me": "mini_me.png",
  "Mint": "mint.png",
  "Molten Core": "molten_core.png",
  "Moth": "moth.png",
  "Mugged": "mugged.png",
  "Near Space": "near_space.png",
  "Neon Flamingo": "neon_flamingo.png",
  "Night Vision": "night_vision.png",
  "Nightstalker": "nightstalker.png",
  "Nil": "nil.png",
  "None": "none.png",
  "Noob": "noob.png",
  "Nothing": "nothing.png",
  "Nuclear": "nuclear.png",
  "Nuggets": "nuggets.png",
  "Nuke": "nuke.png",
  "Null": "null.png",
  "Nyan": "nyan.png",
  "Nyan Ultimate": "nyan_ultimate.png",
  "Obliterator": "obliterator.png",
  "Obsidian": "obsidian.png",
  "Ocean": "ocean.png",
  "OE Dark": "oe_dark.png",
  "OE Light": "oe_light.png",
  "Oil": "oil.png",
  "Ol Faithful": "ol_faithful.png",
  "Oompah": "oompah.png",
  "Ooze": "ooze.png",
  "Ornament": "ornament.png",
  "Palace": "palace.png",
  "Paparazzi": "paparazzi.png",
  "Paul": "paul.png",
  "Paul Ultimate": "paul_ultimate.png",
  "Pawn Shop": "pawn_shop.png",
  "Peacock": "peacock.png",
  "Peacock Ultimate": "peacock_ultimate.png",
  "Pearl": "pearl.png",
  "Peppermint": "peppermint.png",
  "Phoenix": "phoenix.png",
  "Pie": "pie.png",
  "Pizza": "pizza.png",
  "Plastik": "plastik.png",
  "Plate": "plate.png",
  "Plush": "plush.png",
  "Plush Ultimate": "plush_ultimate.png",
  "Poker": "poker.png",
  "Polished": "polished.png",
  "Pop": "pop.png",
  "Porcelain": "porcelain.png",
  "Prickles": "prickles.png",
  "Princess": "princess.png",
  "Projectionist": "projectionist.png",
  "Prom": "prom.png",
  "Purplex": "purplex.png",
  "Pylons": "pylons.png",
  "Pyrex": "pyrex.png",
  "QQQ": "qqq.png",
  "Quilt": "quilt.png",
  "R&B": "r&b.png",
  "Radiance": "radiance.png",
  "Rainbow Morpho": "rainbow_morpho.png",
  "Rattler": "rattler.png",
  "Recon": "recon.png",
  "Ring Blue": "ring_blue.png",
  "Ring Green": "ring_green.png",
  "Ring Red": "ring_red.png",
  "Rose": "rose.png",
  "Ross": "ross.png",
  "Royal": "royal.png",
  "Rug": "rug.png",
  "Rust": "rust.png",
  "Sahara": "sahara.png",
  "Sand": "sand.png",
  "Sap": "sap.png",
  "Satellite": "satellite.png",
  "Saw": "saw.png",
  "Scissors": "scissors.png",
  "Screamo": "screamo.png",
  "Seabiscuit": "seabiscuit.png",
  "Seafoam": "seafoam.png",
  "Shamrock": "shamrock.png",
  "Shark": "shark.png",
  "Shipped": "shipped.png",
  "Silent Film": "silent_film.png",
  "Silicon": "silicon.png",
  "Silver": "silver.png",
  "Sir": "sir.png",
  "Skull Ultimate": "skull_ultimate.png",
  "Sky": "sky.png",
  "Sleet": "sleet.png",
  "Smurf": "smurf.png",
  "Snapshot": "snapshot.png",
  "Snow": "snow.png",
  "Soul": "soul.png",
  "Spaghetti": "spaghetti.png",
  "Spectrum": "spectrum.png",
  "Splatter": "splatter.png",
  "Stained Glass": "stained_glass.png",
  "Stars": "stars.png",
  "Steam": "steam.png",
  "Sterling": "sterling.png",
  "Sticky": "sticky.png",
  "Stock": "stock.png",
  "Stolen": "stolen.png",
  "Stone": "stone.png",
  "Sun": "sun.png",
  "Sunset": "sunset.png",
  "Tactical": "tactical.png",
  "Tangerine": "tangerine.png",
  "Tarpie": "tarpie.png",
  "Taser": "taser.png",
  "Tat": "tat.png",
  "Technicolor": "technicolor.png",
  "Terminator": "terminator.png",
  "Test Track": "test_track.png",
  "The Lethal Dimension": "the_lethal_dimension.png",
  "The Ram": "the_ram.png",
  "Tickle": "tickle.png",
  "Tie Dye": "tie_dye.png",
  "Tiles": "tiles.png",
  "Trapped": "trapped.png",
  "Tron": "tron.png",
  "Ultimate Instruments": "ultimate_instruments.png",
  "Ultimate Weaponry": "ultimate_weaponry.png",
  "Vampire": "vampire.png",
  "Vanished": "vanished.png",
  "Vapor": "vapor.png",
  "Victoria": "victoria.png",
  "Waves": "waves.png",
  "Whiskey": "whiskey.png",
  "White": "white.png",
  "Whiteout": "whiteout.png",
  "Who": "who.png",
  "Wings": "wings.png",
  "Wings Ultimate": "wings_ultimate.png",
  "Wires": "wires.png",
  "X Ray": "x_ray.png",
  "X Ray Ultimate": "x_ray_ultimate.png",
};

export const updateVariationImages = mutation({
  args: {},
  handler: async (ctx) => {
    // Get all variations from the database
    const variations = await ctx.db.query("variationsReference").collect();
    
    let updatedCount = 0;
    let notFoundCount = 0;
    const notFoundNames: string[] = [];
    
    for (const variation of variations) {
      const imageName = VARIATION_IMAGE_MAP[variation.name];
      
      if (imageName) {
        // Update the variation with the image URL
        await ctx.db.patch(variation._id, {
          imageUrl: `/variation-images/${imageName}`
        });
        updatedCount++;
      } else {
        notFoundCount++;
        notFoundNames.push(variation.name);
      }
    }
    
    console.log(`Updated ${updatedCount} variations with image URLs`);
    console.log(`${notFoundCount} variations not found in image map`);
    if (notFoundNames.length > 0) {
      console.log("Variations without images:", notFoundNames);
    }
    
    return {
      success: true,
      updated: updatedCount,
      notFound: notFoundCount,
      notFoundNames
    };
  },
});

// Query to get all variations with their image URLs
export const getVariationsWithImages = mutation({
  args: {},
  handler: async (ctx) => {
    const variations = await ctx.db.query("variationsReference").collect();
    return variations.map(v => ({
      name: v.name,
      type: v.type,
      imageUrl: v.imageUrl || null
    }));
  }
});