/**
 * NMKR Metadata Generator
 *
 * Generates CIP-25 compliant .metadata JSON files for NMKR Studio bulk upload
 *
 * NMKR Workflow:
 * 1. Upload single artwork image (bronze.png) to NMKR
 * 2. Upload multiple .metadata files generated by this tool
 * 3. NMKR creates multiple NFTs all pointing to same IPFS image hash
 */

export interface NMKRMetadataParams {
  collectionName: string;      // "Beta Commemorative"
  tokenBaseName: string;        // "Bronze Token"
  numberOfNFTs: number;         // 5, 35, 100, etc.
  phase: number;                // 1, 2, 3...
  description: string;          // Description template
  imageIpfsHash?: string;       // Optional: "QmXxxx..." or leave empty for NMKR to fill
  artist?: string;              // Default: "Wren Ellis"
  company?: string;             // Default: "Over Exposed"
  game?: string;                // Default: "Mek Tycoon"
}

export interface NMKRMetadataFile {
  filename: string;    // "Bronze Token #1.metadata"
  content: string;     // JSON string
}

/**
 * Generate NMKR-compatible metadata files
 *
 * Creates N metadata JSON files ready for NMKR Studio drag-and-drop upload
 *
 * @param params - Metadata generation parameters
 * @returns Array of {filename, content} objects
 */
export function generateNMKRMetadataFiles(params: NMKRMetadataParams): NMKRMetadataFile[] {
  const files: NMKRMetadataFile[] = [];

  for (let i = 1; i <= params.numberOfNFTs; i++) {
    const metadata = buildSingleNFTMetadata(params, i);
    const filename = `${params.tokenBaseName} #${i}.metadata`;
    const content = JSON.stringify(metadata, null, 2);

    files.push({ filename, content });
  }

  return files;
}

/**
 * Build metadata for a single NFT
 *
 * NMKR Format: Plain JSON object (NOT wrapped in CIP-25 structure)
 * NMKR will wrap this in: { "721": { policyId: { assetName: {...} } } }
 */
function buildSingleNFTMetadata(params: NMKRMetadataParams, editionNumber: number) {
  const imageUrl = params.imageIpfsHash
    ? `ipfs://${params.imageIpfsHash}`
    : 'ipfs://[PLACEHOLDER - NMKR will populate after image upload]';

  return {
    // Required CIP-25 fields
    name: `${params.tokenBaseName} #${editionNumber}`,
    description: params.description,
    image: imageUrl,
    mediaType: inferMediaType(imageUrl),

    // Project-specific metadata
    Collection: params.collectionName,
    Game: params.game || 'Mek Tycoon',
    Artist: params.artist || 'Wren Ellis',
    Company: params.company || 'Over Exposed',
    Phase: params.phase,
    Series: 'Commemorative Tokens',

    // Searchability tags
    tags: [
      params.game || 'Mek Tycoon',
      params.collectionName,
      `Phase ${params.phase}`,
      `#${editionNumber}`
    ],

    // Project info
    project: params.game || 'Mek Tycoon',
    category: 'Commemorative Token',
    website: 'https://mek.overexposed.io'
  };
}

/**
 * Infer media type from image URL
 */
function inferMediaType(url: string): string {
  const lower = url.toLowerCase();

  if (lower.includes('placeholder')) return 'image/png';
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.gif')) return 'image/gif';
  if (lower.endsWith('.webp')) return 'image/webp';
  if (url.startsWith('ipfs://')) return 'image/png';

  return 'image/png';
}

/**
 * Get description template for a phase
 */
export function getDefaultDescription(phase: number, collectionName: string): string {
  return `Exclusive commemorative NFT awarded to Phase ${phase} beta testers of Mek Tycoon. ${collectionName} collection.`;
}

/**
 * Validate metadata parameters
 */
export function validateMetadataParams(params: NMKRMetadataParams): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (!params.collectionName || params.collectionName.trim() === '') {
    errors.push('Collection name is required');
  }

  if (!params.tokenBaseName || params.tokenBaseName.trim() === '') {
    errors.push('Token base name is required');
  }

  if (params.numberOfNFTs < 1 || params.numberOfNFTs > 1000) {
    errors.push('Number of NFTs must be between 1 and 1000');
  }

  if (params.phase < 1) {
    errors.push('Phase must be at least 1');
  }

  if (!params.description || params.description.trim() === '') {
    errors.push('Description is required');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Format filename for download
 */
export function getDownloadFilename(tokenBaseName: string, phase: number): string {
  const sanitized = tokenBaseName.replace(/[^a-zA-Z0-9]/g, '');
  return `${sanitized}_Phase${phase}_metadata.zip`;
}
